apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: knative-demo
spec:
  template:
    spec:
      containers:
        - image: docker.io/adi6496/helloworld-python
    